version: "3.3"
services:
  be:
    image: "cctiv_project:$BUILD_TAG"
    build:
      context: .
      dockerfile: Dockerfile-Python
      args:
        - DEV=true
    ports:
      - "8023:8000"
    command: >
      sh -c "
          uvicorn ailiver.main:app --reload --port 8000 --host 0.0.0.0
        "
    environment:
      - PYTHONPATH=.
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: postgres:15.5-alpine3.18
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5423:5432"
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  dev-db-data: